### ISSUE TITLE
Blink v0.12.6 removed functions `AtomShell.isinstalled()` and `AtomShell.install()` used in KomaMRI.jl

### ISSUE THREAD

**Issue by cncastillo** [cncastillo/KomaMRI.jl#143]
This causes an error when compiling Koma.

**Comment by cncastillo** [comment]
@beorostica  Can you check if this commit fixes the problem? Or is it better to also change the compat of Blink to 0.12.6?

**Comment by beorostica** [comment]
I tested the project with the new commit in a fresh installation with Julia 1.8.4. The UI is working without a any problem.
