### ISSUE TITLE
Koma logo in the docs is incorrect

### ISSUE THREAD

**Issue by cncastillo** [cncastillo/KomaMRI.jl#193]
The logo used in the docs is not the same that the one used in the repo, I would use exactly the same file to about this happeneing again (no duplicates). The newest version is the one with the blue that is less bright.

**Comment by beorostica** [comment]
I'm going to add a common assets folder in the root path of the project, so common logo files must be changed in one place. I linked this to the 'docs' branch.

**Comment by cncastillo** [comment]
This was already fixed.
