### ISSUE TITLE
Bug with Δf in RF_sinc function

### ISSUE THREAD

**Issue by pvillacorta** [cncastillo/KomaMRI.jl#197]
The parameter Δf does not produce the expected effect: it should displace selected slice from (0,0,0).
This problem has not happened until RF_sinc function was introduced.

**Comment by cncastillo** [comment]
Hi Pablo, can you give a minimal working example (MWE) on how to reproduce this problem? As in this example it is working well https://cncastillo.github.io/KomaMRI.jl/stable/generated/lit-04-3DSliceSelective/.

**Comment by pvillacorta** [comment]
I do not have the previous values, but I can show the ones I used for the 3 sliced shown above:


```
T_rf = 1e-3         # Pulse duration
Gss = 5e-3          # Slice-select gradient

α = 45              # Flip angle
B_1° = 2.608134e-7  # With T_rf = 1ms, we need B1 = 2.608134e-7  T to produce a flip angle α = 1°
B1 = α*B_1°         # RF pulse amplitude
```

The only parameter that changes between slices is `Δf`:

- Slice 1:
`Δf = 10e3` (10kHz)

- Slice 2:
`Δf = 0`   (0 kHz)

- Slice 3:
`Δf = -10e3` (-10kHz)
