### ISSUE TITLE
Replicate pulseq functions to create sequences

### ISSUE THREAD

**Issue by beorostica** [cncastillo/KomaMRI.jl#206]
We already have functionality for creating events similar to pulseq functions, for example:

```matlab
% Matlab Pulseq Code
seq = mr.Sequence()
rf = mr.makeBlockPulse(args...)
gr = mr.makeTrapezoid(args...)
adc = mr.makeAdc(args...)
```
```julia
# Julia KomaMRI Code
seq = Sequence()
rf = RF(args...)
gr = Grad(args...)
adc = ADC(args...)
```

However, we don't have all functions for combining events. In matlab pulseq this is done the `addBlock()` function:
```matlab
...
seq.addBlock(rf, gr, adc)
```

The analog combination of event and concatenation in a sequence would be something like this:
```julia
...
seq += (rf, gr, adc)
```

There are many options to be aware when dealing with combination of events, for example we could even sum two gx gradients.

**Comment by cncastillo** [comment]
This isssue is related with https://github.com/cncastillo/KomaMRI.jl/issues/4.
