### ISSUE TITLE
StackOverflowError on plots of large sequences

### ISSUE THREAD

**Issue by gabuzi** [cncastillo/KomaMRI.jl#221]
Hi,
I went a bit more in-depth with Koma and depart from the examples. Trying to import some of our sequences that we use on daily basis seems to cause errors in the plots on my system.

pulseq files were generated with pypulseq and the sequences are small scaled-down examples of what we use (2D Cartesian with 64 phase encode steps and 18 repetitions per step).

Sequence was read with
```Julia repl
julia> using KomaMRI

julia> seq = read_seq("/path/to/seqfile")
Sequence[ τ = 39276.8 ms | blocks: 6912 | ADC: 1152 | GR: 5724 | RF: 1088 | DEF: 9 ]
julia> plot_seq(seq)
ERROR: StackOverflowError:
```

I used v0.7.5 with julia 1.9.1 on macOS and Ubuntu (same behavior).

I opened #220 that addresses this, but it's probably better to have an issue for it as well to give more context.

**Comment by cncastillo** [comment]
Thanks @gabuzi :) Running the CI on the pull 

- https://github.com/cncastillo/KomaMRI.jl/pull/220

If it passes all the tests, it could be an instant merge!
