### ISSUE TITLE
Precompiling KomaMRIPlots hangs on Windows

### ISSUE THREAD

**Issue by cncastillo** [cncastillo/KomaMRI.jl#225]
At least in the master of KomaMRIPlots apparently it has been fixed by downgrading to PlotlyJS 0.18.10.

This issue is associated with:

- https://github.com/JuliaPlots/PlotlyJS.jl/issues/476
- https://github.com/JuliaPlots/PlotlyJS.jl/issues/473
- https://github.com/JuliaPlots/PlotlyKaleido.jl/issues/13

A possible solution for now:
```julia
] add PlotlyJS@0.18.10 # Downgrades PlotlyJS
] add KomamRI
```
@beorostica can you check if this solves the issue?

**Comment by beorostica** [comment]
I cannot replicate the problem on my laptop. However, downgrading is the solution according to [this comment](https://github.com/pulseq/ISMRM-Virtual-Meeting--November-15-17-2023/discussions/15#discussioncomment-7627912).

**Comment by beorostica** [comment]
The patch solution has already been merged into the master branch.

**Comment by cncastillo** [comment]
We are restricting Kaleido_jll = "0.1", which seems to be the most reliable solution. @beorostica should this be closed?

**Comment by beorostica** [comment]
Yes
