### ISSUE TITLE
Margins of plot_signal are not consistent with plot_seq

### ISSUE THREAD

**Issue by cncastillo** [cncastillo/KomaMRI.jl#84]
This is especially noticeable in the documentation.

`plot_seq`:

![image](https://user-images.githubusercontent.com/5957134/186715067-dd97dc36-dafe-44c1-a5cd-e99d625bd6f0.png)

`plot_signal`:

![image](https://user-images.githubusercontent.com/5957134/186715158-e2fb27da-1a81-4ef7-96cd-eef742c07897.png)

**Comment by cncastillo** [comment]
@beorostica can you check if this commit fixes the issue?

**Comment by beorostica** [comment]
Now the margins are looking good in the master branch:

![Screenshot (404)](https://user-images.githubusercontent.com/36004160/187256218-aaa266c9-749c-4e87-8dc8-34ae80f6dd0f.png)

![Screenshot (405)](https://user-images.githubusercontent.com/36004160/187256254-2619f560-f901-447d-9782-2f69681516c1.png)

**Comment by cncastillo** [comment]
What about that space? I think the margins you are showing are for the Plotly container.
![image](https://user-images.githubusercontent.com/5957134/187541065-87379db9-7259-4a15-9684-7acda7c19abd.png)

**Comment by beorostica** [comment]
I think it's a matter of how Plotly manages the sizes of the plot for different axis values, in particular when there are values to show at the edges of a figure. Here I show two examples where the "spaces" of the figures change for different axis values:
 
![Screenshot (410)](https://user-images.githubusercontent.com/36004160/187556544-410801b0-53f2-4761-9816-0298c8c8e131.png)
![Screenshot (411)](https://user-images.githubusercontent.com/36004160/187556553-435e7b25-0f61-46e9-b39d-1b5490032106.png)

![Screenshot (412)](https://user-images.githubusercontent.com/36004160/187556566-c4b0a34b-93f6-4de8-b580-5f531201393f.png)
![Screenshot (413)](https://user-images.githubusercontent.com/36004160/187556574-88ffd820-9caf-47cc-bb32-9414a18e48d6.png)

**Comment by cncastillo** [comment]
I think I have already fixed this in a past commit. I am closing this issue.
